### PR TITLE
fix #1 by adding docs

### LINKED ISSUE #1: Something is broken
The thing is broken!

### PR DESCRIPTION
**Pull request by analogrelay**
Fixes #1 

Blah BLah

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/aspnet/MsftBotPlayground/pull/2)

### CODE REVIEW

**Comment by analogrelay** [comment]
@msftbot please ensure @jkotalik signs off before merging

**Comment by analogrelay** [comment]
@msftbot please use a merge commit

**Comment by analogrelay** [comment]
Guess that didn't work :(

**Review by jkotalik — APPROVED** [review]

**Comment by jkotalik** [comment]
Hey! I think that worked?

**Comment by analogrelay** [comment]
Now we wait :)

**Comment by jkotalik** [comment]
Uh it should def merge faster than 8 hours

**Comment by analogrelay** [comment]
1. Totally configurable (including down to zero I believe)
2. The waiting period is from when the PR is opened, not when final approvals are given. The idea is to give time for it to be seen by appropriate people.

Also...

**Comment by analogrelay** [comment]
@msftbot don't wait to merge this

**Comment by analogrelay** [comment]
@msftbot merge this immediately

**Comment by analogrelay** [comment]
@msftbot wait 1 minute to merge this

**Comment by analogrelay** [comment]
Ok that worked :).

Finally, this only applies to the auto-merge process. If you want to merge it you can always merge it yourself (assuming team practices and branch restrictions have been satisfied).

**Pull request merged**
